### PR TITLE
Update Scala Native to 0.4.1

### PR DESCRIPTION
**Pull request by lolgab**
- Update dependencies
- Support Scala 2.13
- Fix warnings

~There is a test which if failing with a crash related to malloc.. Which it might be related to scala-native-loop.
I have to investigate it, otherwise it seems good to go~
The issue is present in the master branch too and it's unrelated with this PR

### CODE REVIEW

**Review by david-bouyssie — APPROVED** [review]
It looks good to me.
Thank you very much for this PR Lorenzo!

**Comment by lolgab** [comment]
Can you add the #hacktoberfest-accepted label to this PR? :-D

**Comment by david-bouyssie** [comment]
Like this?

**Comment by lolgab** [comment]
Yes, thank you :)

**Pull request merged**
